image: mcr.microsoft.com/dotnet/sdk:7.0

# List of stages for jobs, and their order of execution
stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker-build
  script:
    - apt-get update -y
    - apt-get upgrade -y
    - dotnet --version