### This .gitlab-ci.yml is based on the official dotnet template for gitlab
### https://gitlab.com/gitlab-org/project-templates/dotnetcore

image: mcr.microsoft.com/dotnet/sdk:6.0
  
# List of stages for jobs, and their order of execution
stages:
  - build
  - test
  - publish
  - deploy

### Define variables
variables:
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'BoomBoxWeb/'

### Define global cache
cache:
  key: "CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    # Path to the directory where restored dependencies are kept.
    - '$NUGET_PACKAGES_DIRECTORY'

  # 'pull-push' policy means that latest cache will be downloaded (if it exists)
  # before executing the job, and a newer version will be uploaded afterwards.
  policy: pull-push

### Restore project dependencies
before_script:
  # Change to the correct directory
  - 'cd $SOURCE_CODE_PATH'
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

build:
  stage: build
  ### Set the correct tag for the `Shared Gitlab Runners`
  tags:
    - docker-build
  script:
    - 'dotnet build --no-restore'

test:
  stage: test
  tags:
    - docker-build
  script:
    - 'dotnet test --no-restore'

publish:
  stage: publish
  tags:
    - docker-build
  script:
    - 'dotnet publish -c Release -o ./publish --no-restore'
  artifacts:
    paths:
      - BoomBoxWeb/publish/

deploy:
  stage: deploy
  tags:
    - docker-build
  image: node:lts-alpine
  before_script: # Override previous before_script
    - 'cd $SOURCE_CODE_PATH' 
  script:
    - 'npm install netlify-cli'
    - ls -a
    - 'cd publish/wwwroot'
    - 'netlify deploy --prod --dir=. --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID'
